function [BW,maskedImage] = segmentImageProcessingWithoutKLGrade(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 20-Oct-2024
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask
BW = false(size(X,1),size(X,2));

% Flood fill
row = 1104;
column = 671;
tolerance = 1.300000e-01;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Flood fill
row = 1191;
column = 1737;
tolerance = 1.800000e-01;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Active contour
iterations = 100;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Dilate mask with default
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Dilate mask with rectangle
dimensions = [3 3];
se = strel('rectangle', dimensions);
BW = imdilate(BW, se);

% Fill holes
BW = imfill(BW, 'holes');

% Fill holes
BW = imfill(BW, 'holes');

% Local graph cut
xPos = [533.4207 580.3052 592.8077 517.7925 514.6669 511.5412 514.6669 527.1694 633.4410 1080.4067 986.6377 1058.5273 992.8890 1092.9093 955.3813 1086.6580 1164.7989 ];
yPos = [11.4223 339.0920 741.6576 1000.6727 1175.4299 1300.2564 1440.6863 1556.1508 2067.9397 2061.6983 1999.2851 1837.0106 1587.3575 1078.6893 782.2262 454.5566 11.4223 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,25580,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Local graph cut
xPos = [1830.5590 1643.0209 1533.6237 1549.2519 1530.4981 1643.0209 1658.6491 1996.2176 2111.8661 2071.2329 2064.9816 2102.4892 2049.3534 2158.7506 ];
yPos = [11.4223 822.7949 960.1041 1191.0332 1318.9804 1515.5822 2061.6983 2067.9397 1493.7376 1290.8944 1119.2579 897.6908 663.6410 11.4223 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [];
backgroundInd = [];
L = superpixels(X,31185,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = BW | grabcut(scaledX,L,ROI,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1) = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2) = (in(:,:,2) + 86.1827) / 184.4170;  % a* range is [-86.1827,98.2343].
out(:,:,3) = (in(:,:,3) + 107.8602) / 202.3382;  % b* range is [-107.8602,94.4780].

end
